### ISSUE TITLE
It crashes when there are two devices with same serial numbers

### ISSUE THREAD

**Issue by iballan** [camalot/madb#1]
C:\Users\MBH>adb devices
List of devices attached
0123456789ABCDEF        device
0123456789ABCDEF        device

both of them are connected at the same time

but madb crashes here

**Comment by camalot** [comment]
I understand that this is 2 different devices, but, how would you expect it to be able to identify these are 2 different devices? I am not saying that it should crash, because it shouldn't. But the device ID is what is used to connect to a specific device. Those are not real device IDs. That is the "default" device ID that is assigned when the real device ID cannot be identified.

**Comment by camalot** [comment]
2 months, no response, I am closing this. Feel free to comment to reopen.
